# 使用双引号（与 eslint-config-prettier 默认一致）
singleQuote: false
# 行尾需要有分号
semi: true
# 一行最多 100 字符
printWidth: 100
# 尾随逗号
trailingComma: all
# 使用 2 个空格缩进
tabWidth: 2
# 用制表符代替空格缩进行
useTabs: false
# 更改对象中的属性是否加引号
quoteProps: as-needed
# 大括号内的首尾需要空格
bracketSpacing: true
# 箭头函数，只有一个参数的时候，也需要括号
arrowParens: always
# 使用默认的折行标准
proseWrap: preserve
# 根据显示样式决定 html 要不要折行
htmlWhitespaceSensitivity: css
# 换行符使用 lf
endOfLine: lf
# 将多行 HTML 元素的 > 放在最后一行的末尾
bracketSameLine: true
# 仅格式化文件的一个区段
rangeStart: 0
# 只格式化文件顶部包含特殊注释的文件
requirePragma: false
# 不自动插入 @format 标记
insertPragma: false
# 是否缩进 Vue 文件中 <script> 和 <style> 标记内的代码
vueIndentScriptAndStyle: false
# 在 HTML、Vue 和 JSX 中每行强制单个属性
singleAttributePerLine: false
